// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH99MUrEyOGpG9UeyJXOyvcSeRlZtHh8g',
    appId: '1:597476018138:web:d0094a31132e84adf0e2e3',
    messagingSenderId: '597476018138',
    projectId: 'carcount-4d874',
    authDomain: 'carcount-4d874.firebaseapp.com',
    storageBucket: 'carcount-4d874.firebasestorage.app',
    measurementId: 'G-056BP9VY2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLsXK7Au08A-ozcj57IDipn6eykUqejsE',
    appId: '1:597476018138:android:6d75eb0c4377a603f0e2e3',
    messagingSenderId: '597476018138',
    projectId: 'carcount-4d874',
    storageBucket: 'carcount-4d874.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDblfJ6OnZljAb6zuQfjp1HG945Hb9rXB4',
    appId: '1:597476018138:ios:16b4fa1bf0cc3d23f0e2e3',
    messagingSenderId: '597476018138',
    projectId: 'carcount-4d874',
    storageBucket: 'carcount-4d874.firebasestorage.app',
    iosBundleId: 'com.example.carcount',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDblfJ6OnZljAb6zuQfjp1HG945Hb9rXB4',
    appId: '1:597476018138:ios:16b4fa1bf0cc3d23f0e2e3',
    messagingSenderId: '597476018138',
    projectId: 'carcount-4d874',
    storageBucket: 'carcount-4d874.firebasestorage.app',
    iosBundleId: 'com.example.carcount',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH99MUrEyOGpG9UeyJXOyvcSeRlZtHh8g',
    appId: '1:597476018138:web:fa35b2166e3e3efcf0e2e3',
    messagingSenderId: '597476018138',
    projectId: 'carcount-4d874',
    authDomain: 'carcount-4d874.firebaseapp.com',
    storageBucket: 'carcount-4d874.firebasestorage.app',
    measurementId: 'G-6DVBK0DEWV',
  );
}
